on: workflow_dispatch

name: Submit to Webstores

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - name: Install
        run: npm install
      - name: Package
        run: bash pack.sh
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        with:
          artifact: "./dictionaries.zip"
          keys: ${{ secrets.SUBMIT_KEYS }}
